// src/Questionnaire.js

const questions = [
  { id: 1, text: "Unsere Mitarbeitenden werden regelmäßig zu Nachhaltigkeit und globalen Zielen fortgebildet." },
  { id: 2, text: "Nachhaltigkeit wird systematisch in unsere Programmplanung integriert." },
  { id: 3, text: "Unsere Bildungsangebote orientieren sich an Prinzipien wie Partizipation, Lebensweltbezug und Zukunftsfähigkeit." },
  { id: 4, text: "Wir fördern bei Teilnehmenden das Erkennen globaler Zusammenhänge." },
  { id: 5, text: "Wir bieten regelmäßig Angebote zu ökologischen, sozialen und wirtschaftlichen Themen an, die zu nachhaltigem Handeln im Alltag anregen." },
  { id: 6, text: "Wir holen Rückmeldungen zu Bewusstsein und Handlungsbereitschaft ein." },
  { id: 7, text: "Wir analysieren unseren Beitrag zu globalen Zielen mit Hilfe von Indikatoren." },
  { id: 8, text: "Evaluationsergebnisse werden genutzt, um unsere Angebote weiterzuentwickeln." },
  { id: 9, text: "Unsere Einrichtung achtet auf einen ressourcenschonenden Alltag (Energie, Abfall, Beschaffung)." },
  { id: 10, text: "Werte wie Solidarität, Gerechtigkeit und Umweltbewusstsein werden aktiv gelebt." },
  { id: 11, text: "Unsere Einrichtung arbeitet mit Partnern zusammen, die ebenfalls für Nachhaltigkeit stehen." },
  { id: 12, text: "Armut wird in unserer Region als relevantes Thema wahrgenommen." },
  { id: 13, text: "Unsere Einrichtung hat sich bereits in Projekten gegen Armut engagiert." },
  { id: 14, text: "Besucher*innen mit unterschiedlichen sprachlichen oder kulturellen Hintergründen fühlen sich angesprochen." },
  { id: 15, text: "Bei der Angebotsplanung werden verschiedene Zielgruppen aktiv einbezogen." },
  { id: 16, text: "Es finden regelmäßig Angebote zu Ernährung, Hunger, nachhaltiger Landwirtschaft und Gesundheitsthemen statt." },
  { id: 17, text: "Der Bezug zur Lebenswelt der Teilnehmenden wird bei den Themen Ernährung und Gesundheit berücksichtigt." },
  { id: 18, text: "Die Relevanz der Themen Ernährung und Gesundheit wird für unsere Zielgruppe als hoch eingeschätzt." },
  { id: 19, text: "Individuelle Lern- und Entwicklungsbedürfnisse der Kinder werden berücksichtigt." },
  { id: 20, text: "Kinder können eigene Ideen oder Themen in den Alltag einbringen." },
  { id: 21, text: "Es gibt gezielte Angebote zur Förderung sozialer Kompetenzen." },
  { id: 22, text: "Verschiedene Lernformen werden bewusst in den Alltag integriert." },
  { id: 23, text: "Inwieweit trägt Ihre Einrichtung dazu bei, Bildungsangebote unabhängig von sozialer oder kultureller Herkunft zugänglich zu machen?" },
  { id: 24, text: "Unsere Einrichtung stellt sicher, dass Kinder unabhängig von ihrem Geschlecht gleichberechtigt an allen Bildungsangeboten teilnehmen können." },
  { id: 25, text: "Inwieweit spiegeln die in Ihrer Einrichtung verwendeten Materialien unterschiedliche Lebensrealitäten und Rollenbilder wider, um Diversität und Inklusion zu fördern?" },
  { id: 26, text: "Geschlechterspezifische Bedürfnisse werden pädagogisch berücksichtigt." },
  { id: 27, text: "Im Alltag wird auf sparsamen Umgang mit Wasser und Energie geachtet und entsprechende Maßnahmen werden umgesetzt." },
  { id: 28, text: "Die Einrichtung beteiligt sich an Initiativen zum Schutz von Wasserressourcen." },
  { id: 29, text: "Energie- und wasserbezogene Themen werden regelmäßig in Angeboten behandelt, wobei verschiedene Energieformen thematisiert und der Bezug zur Lebenswelt der Teilnehmenden hergestellt wird." },
  { id: 30, text: "Geräte wie Computer oder Projektoren werden möglichst lange genutzt." },
  { id: 31, text: "Mit dem Thema Digitalisierung wird reflektiert umgegangen." },
  { id: 32, text: "Abfallvermeidung wird aktiv betrieben." },
  { id: 33, text: "Die Mobilität der Mitarbeitenden wird nachhaltig gestaltet." },
  { id: 34, text: "Der Umgang mit Papier, Wasser und Energie ist ressourcenschonend organisiert." },
  { id: 35, text: "Es gibt Projekte zur Sensibilisierung für bewussten Konsum." },
  { id: 36, text: "Die Einrichtung engagiert sich in Projekten zum Umwelt-, Natur- und Artenschutz (z.B. Schutz von Meeren, Wäldern oder Tieren)." },
  { id: 37, text: "Beim Einkauf wird auf nachhaltige Produkte geachtet." },
  { id: 38, text: "Die Einrichtung reflektiert regelmäßig ihre eigenen Nachhaltigkeitsziele und -maßnahmen." },
  { id: 39, text: "Unsere Einrichtung kooperiert aktiv mit lokalen und globalen Partnern für nachhaltige Entwicklung." },
  { id: 40, text: "Wir nehmen regelmäßig an Fortbildungen und Netzwerktreffen zum Thema BNE teil." }
];

export default questions;
